name: SSH

on:
  workflow_dispatch:

jobs:
  ai:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
        - name: Debug through SSH
          uses: edipizarro/runner-open-ssh@main
          with:
            sshPublicKey: ${{ secrets.SSH_PUBLIC_KEY }}
            gatewayPrivateKey: ${{ secrets.GATEWAY_PRIVATE_KEY }}
            gatewayIP: ${{ secrets.GATEWAY_IP }}
            gatewayUser: ${{ secrets.GATEWAY_USER }}
            maxLifeTime: 30
            port: 2222  # Optional: defaults to 2222
